import { Poppins } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/providers/redux-provider";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { Navbar01 } from "@/components/ui/shadcn-io/navbar-01";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <ReduxProvider>
          <QueryProvider>
            <div className="min-h-screen w-full relative">
              <div className="absolute inset-0 z-0" />
              <div className="relative z-10 bg-zinc-50">
                <Navbar01 />
                {children}
              </div>
            </div>
            <Toaster />
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
