import { Poppins } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/providers/redux-provider";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <ReduxProvider>
          <QueryProvider>
            <div className="min-h-screen w-full bg-[#f0fdfa] relative">
              <div
                className="absolute inset-0 z-0"
                style={{
                  backgroundImage: `
                    linear-gradient(45deg, 
                      rgba(240,253,250,1) 0%, 
                      rgba(204,251,241,0.7) 30%, 
                      rgba(153,246,228,0.5) 60%, 
                      rgba(94,234,212,0.4) 100%
                    ),
                    radial-gradient(circle at 40% 30%, rgba(255,255,255,0.8) 0%, transparent 40%),
                    radial-gradient(circle at 80% 70%, rgba(167,243,208,0.5) 0%, transparent 50%),
                    radial-gradient(circle at 20% 80%, rgba(209,250,229,0.6) 0%, transparent 45%)
                  `,
                }}
              />
              <div className="relative z-10">{children}</div>
            </div>
            <Toaster />
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
